// This file is generated by Sim IDX. Do not edit manually.
import { pgEnum, pgTable as table } from "drizzle-orm/pg-core";
import * as t from "drizzle-orm/pg-core";
import { db, types } from "@duneanalytics/sim-idx";

export const preLiquidationHealth = table("pre_liquidation_health", {
  chainbytes32: db.uint64('chainbytes32'),
  txHash: db.bytes32('tx_hash'),
  ltv: db.uint256('ltv'),
})
